{
 "title": "AT&T BGW320",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "modem",
    "label": "Modem",
    "query": {
     "query": "label_values(modemprobe_collector,modem)"
    }
   },
   {
    "name": "ports",
    "label": "Ports",
    "query": {
     "query": "label_values(modemprobe_lan_state,port)"
    }
   },
   {
    "name": "frequencies",
    "label": "WiFi Frequency",
    "query": {
     "query": "label_values(modemprobe_lan_wifistatus_wifiradiostatus{modem=\"$modem\"},frequency)"
    }
   }
  ]
 },
 "panels": [
  { "title": "QUICK LOOK", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "LINK STATE",
   "type": "stat",
   "description": "Indicates if the link is operational.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modemprobe_device_linkstate{modem=~\"$modem\", name!=\"\"}",
     "legendFormat": "LINK STATE"
    }
   ]
  },
  {
   "title": "PORT STATE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modemprobe_lan_state{modem=~\"$modem\", port=~\"$ports\"}",
     "legendFormat": "{{port}}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Time since the device was restarted.",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modemprobe_system_timesincelastreboot{modem=~\"$modem\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "TRANSMIT SPEED",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modemprobe_lan_transmit_speed{modem=~\"$modem\", port=~\"$ports\"}",
     "legendFormat": "{{port}}"
    }
   ]
  },
  {
   "type": "gauge",
   "description": "VOLTAGE",
   "gridPos": { "h": 6, "w": 4, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modemprobe_device_vcc{modem=\"$modem\", name=\"Vcc\"}",
     "legendFormat": "VOLTAGE"
    }
   ]
  },
  {
   "type": "gauge",
   "description": "System is stable when current value is between low and high warning/alarm thresholds.",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modemprobe_device_temperature{modem=\"$modem\", name=\"Temperature\"}",
     "legendFormat": "TEMPERATURE"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(modemprobe_broadband_ipv4_receivebytes{modem=~\"$modem\"}[$__range]))",
     "legendFormat": "RX OVER RANGE"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Time since the CPE first both successfully established an IP-layer network connection and acquired an absolute time reference using NTP or equivalent over that network connection. The CPE MAY reset this date after a factory reset.",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modemprobe_system_firstusedate {modem=~\"$modem\", name!=''}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "LASER WAVELENGTH",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "nm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modemprobe_device_wavelength{modem=~\"$modem\", name!=''}",
     "legendFormat": "Laser {{name}}"
    }
   ]
  },
  {
   "title": "WI-FI RADIO",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modemprobe_lan_wifistatus_wifiradiostatus{modem=~\"$modem\", frequency=~\"$frequencies\"}",
     "legendFormat": "{{frequency}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(modemprobe_broadband_ipv4_transmitbytes{modem=~\"$modem\"}[$__range]))",
     "legendFormat": "TX OVER RANGE"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Tx Bias in amperes/500,000",
   "gridPos": { "h": 2, "w": 5, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modemprobe_device_txbias{modem=~\"$modem\", name!=''}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "NETWORK INFO",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "modemprobe_lan_networkstatus_info{modem=~\"$modem\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WIFI INFO",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 7 },
   "targets": [
    {
     "expr": "modemprobe_lan_wifistatus_info{modem=~\"$modem\", frequency=~\"$frequencies\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SYSTEM INFO",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "modemprobe_system_info{value!=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BROADBAND INFO",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 7 },
   "targets": [
    {
     "expr": "modemprobe_broadband_info{value!=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "NETWORK TRAFFIC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "NETWORK TRAFFIC BYTES",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(modemprobe_lan_transmit_bytes{port=~\"$ports\", modem=~\"$modem\"}[5m])",
     "legendFormat": "TX LAN ({{port}})"
    },
    {
     "expr": "(irate(modemprobe_lan_receive_bytes{port=~\"$ports\", modem=~\"$modem\"}[5m]))",
     "legendFormat": "RX LAN ({{port}})"
    },
    {
     "expr": "(irate(modemprobe_broadband_ipv4_receivebytes{modem=~\"$modem\"}[5m]))",
     "legendFormat": "RX WAN (ipv4)"
    },
    {
     "expr": "irate(modemprobe_broadband_ipv4_transmitbytes{modem=~\"$modem\"}[5m])",
     "legendFormat": "TX WAN (ipv4)"
    },
    {
     "expr": "irate(modemprobe_lan_wifistatistics_transmitbytes{modem=~\"$modem\", frequency=~\"$frequencies\"}[5m])",
     "legendFormat": "TX LAN ({{frequency}})"
    },
    {
     "expr": "irate(modemprobe_lan_wifistatistics_receivebytes{modem=~\"$modem\", frequency=~\"$frequencies\"}[5m])",
     "legendFormat": "RX LAN ({{frequency}})"
    }
   ]
  },
  {
   "title": "NETWORK TRAFFIC BYTES",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(modemprobe_lan_transmit_bytes{port=~\"$ports\", modem=~\"$modem\"}[5m])) by (port)",
     "legendFormat": "TX LAN ({{port}})"
    },
    {
     "expr": "sum(rate(modemprobe_lan_receive_bytes{port=~\"$ports\", modem=~\"$modem\"}[5m])) by (port)",
     "legendFormat": "RX LAN ({{port}})"
    },
    {
     "expr": "sum((rate(modemprobe_broadband_ipv4_receivebytes{modem=~\"$modem\"}[5m])))",
     "legendFormat": "RX WAN (ipv4)"
    },
    {
     "expr": "sum(rate(modemprobe_broadband_ipv4_transmitbytes{modem=~\"$modem\"}[5m]))",
     "legendFormat": "TX WAN (ipv4)"
    },
    {
     "expr": "sum(rate(modemprobe_lan_wifistatistics_transmitbytes{modem=~\"$modem\", frequency=~\"$frequencies\"}[5m])) by (frequency)",
     "legendFormat": "TX LAN ({{frequency}})"
    },
    {
     "expr": "sum(rate(modemprobe_lan_wifistatistics_receivebytes{modem=~\"$modem\", frequency=~\"$frequencies\"}[5m])) by (frequency)",
     "legendFormat": "RX LAN ({{frequency}})"
    }
   ]
  },
  {
   "title": "NETWORK TRAFFIC DROPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(modemprobe_broadband_ipv4_transmitdrops{modem=~\"$modem\"}[5m])",
     "legendFormat": "TX WAN (ipv4)"
    },
    {
     "expr": "irate(modemprobe_broadband_ipv4_receivedrops{modem=~\"$modem\"}[5m])",
     "legendFormat": "RX WAN (ipv4)"
    }
   ]
  },
  {
   "title": "NETWORK TRAFFIC BY PACKETS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(modemprobe_lan_transmit_packets{modem=~\"$modem\", port=~\"$ports\"}[5m])",
     "legendFormat": "TX LAN ({{port}})"
    },
    {
     "expr": "(irate(modemprobe_lan_ipv4_receivepackets{modem=~\"$modem\"}[5m]))",
     "legendFormat": "RX LAN (ipv4)"
    },
    {
     "expr": "(irate(modemprobe_lan_receive_packets{modem=~\"$modem\", port=~\"$ports\"}[5m]))",
     "legendFormat": "RX LAN ({{port}})"
    },
    {
     "expr": "(irate(modemprobe_lan_ipv4_transmitpackets{modem=~\"$modem\"}[5m]))",
     "legendFormat": "TX LAN (ipv4)"
    },
    {
     "expr": "irate(modemprobe_lan_wifistatistics_transmitpackets{modem=~\"$modem\", frequency=~\"$frequencies\"}[5m])",
     "legendFormat": "TX WIFI ({{frequency}})"
    },
    {
     "expr": "(irate(modemprobe_lan_wifistatistics_receivepackets{modem=~\"$modem\", frequency=~\"$frequencies\"}[5m]))",
     "legendFormat": "RX WIFI ({{frequency}})"
    }
   ]
  },
  {
   "title": "NETWORK TRAFFIC MULTICAST",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(modemprobe_lan_transmit_multicast{modem=~\"$modem\", port=~\"$ports\"}[5m])",
     "legendFormat": "TX LAN ({{port}})"
    },
    {
     "expr": "irate(modemprobe_lan_receive_multicast{modem=~\"$modem\", port=~\"$ports\"}[5m])",
     "legendFormat": "RX LAN ({{port}})"
    },
    {
     "expr": "irate(modemprobe_broadband_ipv4_receivemulticast{modem=~\"$modem\"}[5m])",
     "legendFormat": "RX WAN (ipv4)"
    },
    {
     "expr": "irate(modemprobe_broadband_ipv4_transmitmulticast{modem=~\"$modem\"}[5m])",
     "legendFormat": "TX WAN (ipv4)"
    }
   ]
  },
  {
   "title": "NETWORK TRAFFIC ERRORS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(modemprobe_lan_ipv4_transmiterrors{modem=~\"$modem\"}[5m])",
     "legendFormat": "TX LAN (ipv4)"
    },
    {
     "expr": "irate(modemprobe_lan_ipv4_receiveerrors{modem=~\"$modem\"}[5m])",
     "legendFormat": "RX LAN (ipv4)"
    },
    {
     "expr": "irate(modemprobe_lan_transmit_errors{modem=~\"$modem\", port=~\"$ports\"}[5m])",
     "legendFormat": "TX ({{port}})"
    },
    {
     "expr": "irate(modemprobe_lan_receive_errors{modem=~\"$modem\", port=~\"$ports\"}[5m])",
     "legendFormat": "RX ({{port}})"
    },
    {
     "expr": "irate(modemprobe_broadband_ipv6_transmiterrors{modem=~\"$modem\"}[5m])",
     "legendFormat": "TX WAN (ipv6)"
    },
    {
     "expr": "irate(modemprobe_broadband_ipv6_receiveerrors{modem=~\"$modem\"}[5m])",
     "legendFormat": "RX WAN (ipv6)"
    },
    {
     "expr": "irate(modemprobe_broadband_ipv4_receiveerrors{modem=~\"$modem\"}[5m])",
     "legendFormat": "RX WAN (ipv4)"
    },
    {
     "expr": "irate(modemprobe_broadband_ipv4_transmiterrors{modem=~\"$modem\"}[5m])",
     "legendFormat": "TX WAN (ipv4)"
    }
   ]
  },
  {
   "title": "INTERFACE CLIENTS",
   "type": "timeseries",
   "description": "Indicates the status of the various LAN interfaces and the device count, active and inactive, for each interface. The device counts include both DHCP and static clients.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "modemprobe_lan_interface{status=\"Enabled\", modem=~\"$modem\"}",
     "legendFormat": "{{interface}} : {{mode}} clients"
    }
   ]
  },
  {
   "title": "NETWORK TRAFFIC UNICAST",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(modemprobe_lan_transmit_unicast{modem=~\"$modem\", port=~\"$ports\"}[5m])",
     "legendFormat": "TX LAN ({{port}})"
    },
    {
     "expr": "irate(modemprobe_lan_receive_unicast{modem=~\"$modem\", port=~\"$ports\"}[5m])",
     "legendFormat": "RX LAN ({{port}})"
    },
    {
     "expr": "irate(modemprobe_broadband_ipv4_receiveunicast{modem=~\"$modem\"}[5m])",
     "legendFormat": "RX WAN (ipv4)"
    },
    {
     "expr": "irate(modemprobe_broadband_ipv4_transmitunicast{modem=~\"$modem\"}[5m])",
     "legendFormat": "TX WAN (ipv4)"
    }
   ]
  },
  {
   "title": "DEVICE THRESHOLD LOW WARNING",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modemprobe_device_warning{type=\"low\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "DEVICE THRESHOLD LOW ALERT",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modemprobe_device_alarm{type=\"low\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "DEVICE THRESHOLD HIGH WARNING",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modemprobe_device_warning{type=\"high\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "DEVICE THRESHOLD HIGH ALERT",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modemprobe_device_alarm{type=\"high\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "INTERFACES",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp(sum(modemprobe_lan_interface{modem=~\"$modem\", status=\"Disabled\"}) by (interface),0, 1)",
     "legendFormat": "{{interface}}"
    },
    {
     "expr": "clamp(count(modemprobe_lan_interface{modem=~\"$modem\", status=\"Enabled\"}) by (interface),0,1)",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "NETWORK OPERATIONAL STATUS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modemprobe_broadband_linestate{modem=~\"$modem\", name=\"Line State\"}",
     "legendFormat": "LINE"
    },
    {
     "expr": "modemprobe_broadband_unistatus{modem=~\"$modem\", name=\"UNI Status\"}",
     "legendFormat": "UNI - User Network Interface"
    },
    {
     "expr": "modemprobe_device_linkstate{modem=~\"$modem\", name=\"Link State\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "modemprobe_lan_state{modem=~\"$modem\", port=~\"$ports\", name=\"State\"}",
     "legendFormat": "{{port}}"
    },
    {
     "expr": "modemprobe_device_opticalwanoperationalstatus{modem=~\"$modem\", name=\"Optical WAN Operational Status\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "WIFI BANDS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "modemprobe_lan_wifistatus_info{modem=~\"$modem\", frequency=~\"$frequencies\", value=~\"[a-zA-Z][^/]{0,}\", name=\"Mode\"}",
     "legendFormat": "{{frequency}} {{value}}"
    }
   ]
  },
  {
   "title": "TEMPERATURE / VOLTAGE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "title": "TEMPERATURE",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "modemprobe_device_temperature{modem=~\"$modem\", name=\"Temperature\"}\r\n",
       "legendFormat": "{{modem}}"
      },
      {
       "expr": "modemprobe_device_threshold{sensor=\"temperature\", type=\"alarm\", threshold=\"high\", modem=~\"$modem\"}",
       "legendFormat": "{{type}} : {{threshold}}"
      },
      {
       "expr": "modemprobe_device_threshold{sensor=\"temperature\", type=\"alarm\", threshold=\"high\", modem=~\"$modem\"} + 20",
       "legendFormat": "{{type}} : {{threshold}} : top"
      },
      {
       "expr": "modemprobe_device_threshold{sensor=\"temperature\", type=\"alarm\", threshold=\"low\", modem=~\"$modem\"}",
       "legendFormat": "{{type}} : {{threshold}}"
      },
      {
       "expr": "modemprobe_device_threshold{sensor=\"temperature\", type=\"alarm\", threshold=\"low\", modem=~\"$modem\"} - 10",
       "legendFormat": "{{type}} : {{threshold}} : bottom"
      }
     ]
    },
    {
     "title": "VOLTAGE",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "expr": "modemprobe_device_vcc{modem=~\"$modem\"}",
       "legendFormat": "{{model}}"
      },
      {
       "expr": "modemprobe_device_threshold{sensor=\"vcc\", type=\"alarm\", threshold=\"high\", modem=~\"$modem\"}",
       "legendFormat": "{{type}} : {{threshold}}"
      },
      {
       "expr": "modemprobe_device_threshold{sensor=\"vcc\", type=\"alarm\", threshold=\"high\", modem=~\"$modem\"} + 1",
       "legendFormat": "{{type}} : {{threshold}} : top"
      },
      {
       "expr": "modemprobe_device_threshold{sensor=\"vcc\", type=\"alarm\", threshold=\"low\", modem=~\"$modem\"}",
       "legendFormat": "{{type}} : {{threshold}}"
      }
     ]
    },
    {
     "title": "RX POWER",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "mwatt" } },
     "targets": [
      {
       "expr": "modemprobe_device_rxpower{modem=~\"$modem\"}",
       "legendFormat": "RX"
      },
      {
       "expr": "modemprobe_device_threshold{sensor=\"rxpower\", type=\"alarm\", threshold=\"high\", modem=~\"$modem\"}",
       "legendFormat": "{{type}} : {{threshold}}"
      },
      {
       "expr": "modemprobe_device_threshold{sensor=\"rxpower\", type=\"alarm\", threshold=\"high\", modem=~\"$modem\"} + 3",
       "legendFormat": "{{type}} : {{threshold}} : top"
      },
      {
       "expr": "modemprobe_device_threshold{sensor=\"rxpower\", type=\"alarm\", threshold=\"low\", modem=~\"$modem\"}",
       "legendFormat": "{{type}} : {{threshold}}"
      }
     ]
    },
    {
     "title": "TX POWER",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "mwatt" } },
     "targets": [
      {
       "expr": "modemprobe_device_txpower{modem=~\"$modem\"}",
       "legendFormat": "TX"
      },
      {
       "expr": "modemprobe_device_threshold{sensor=\"txpower\", type=\"alarm\", threshold=\"high\", modem=~\"$modem\"} + 25",
       "legendFormat": "{{type}} : {{threshold}}"
      },
      {
       "expr": "modemprobe_device_threshold{sensor=\"txpower\", type=\"alarm\", threshold=\"high\", modem=~\"$modem\"} + 60",
       "legendFormat": "{{type}} : {{threshold}} : top"
      },
      {
       "expr": "modemprobe_device_threshold{sensor=\"txpower\", type=\"alarm\", threshold=\"low\", modem=~\"$modem\"}",
       "legendFormat": "{{type}} : {{threshold}}"
      }
     ]
    }
   ]
  },
  { "title": "MODEM PROBE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "modemprobe_collector{modem=~\"$modem\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 70 },
   "targets": [
    {
     "expr": "modemprobe_probe{modem=~\"$modem\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PROBE ERRORS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "targets": [
    {
     "expr": "modemprobe_probe_errors{modem=~\"$modem\"}",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}